# Generated by Django 3.2 on 2022-03-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220328_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'ordering': ('-created',), 'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
    ]
