version: '3.8'

volumes:
  backend_data:
  backend_static:

services:
  db:
    image: postgres:13.2
    restart: always
    volumes:
      - backend_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  backend:
    build: .
    restart: always
    volumes: 
      - backend_static:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.20.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - backend_static:/var/html/static/
    ports:
      - 80:80
    depends_on:
      - backend
